language: java
jdk:
  - openjdk8

sudo: false

services:
  - docker

branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^issue.*$/"
    - "/^hotfix.*$/"

before_script:
  - "./bin/version.sh"

script:
  - mvn clean install -q || travis_terminate 1

before_install:
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv
    -in gpg.asc.enc -out gpg.asc -d

env:
  global:
    # OSSRH_USERNAME
    - secure: "HXSUM1NvgAxAlpPSFtNQaK0ZtR6NbKaws0A9ZR3VqhvELT4uf7Tf9z6Cdo2obRMTWLT4EiLgVjt/TkwAtMjFAb78pC5RWyZ7+5cP7PKI4edSQuQgr2ixrq0/9Pvtub2Xb28fk7S0xesEtTaHBtZMdIe37OL/B+pcLOkaG3DzdKfNxHVQlVZ3YaY/2vk1EhCmBlaG6WHk3kskkf7NPUZLPpWTqg9KYeoJgvBXw89redSJ7qdI8p8f8CMfaNTZfCLfo13CEzeMPwlKZGzl3pQUsHXnrCnsssJttq4MBJ/i14GnwPNnh/mX/3IMIIk6+0B2pBQW3pH0dhBEXst39Cqcce8TXqpobYBiU6tGJEHEptiT/ajIZHfzBi4U8JkNqQQ2MpZ14tZ6jjgvVp+BuYKBx+Wq08c5keqkUgRIGfIdeYMVhZ9fsKhMqbhWJZd97Zv68OXrrM++MZjZ2qF5NjKIxYh2dkRzAfz/mqqwigTqGEZRt68so9aoufvNskWd2MMD8gOZmjPxoJ3GEBWgwDIyyvuf+ImeOgOGFni2Fq3DpwZcSQ0zCe5Yv7gksR1g+/29UXTC2iOEUj28d294yugukWk2QxPOZcPbxxer2FeeBXSbXKsn2gpfVtTC1sgIc55R++KyMlL1fGPJTnggpmHtZ01/cmFWPKkp3QirifjT/Z4="
    # OSSRH_PASSWORD
    - secure: "V30kibZa6vNAc+sUKdYQnS+gZUL0AO/6+9lWYbcWGzZXIDX1S3U/fb0U1VCCVyltWBHJ58PqdGUHCoZ+2bNkfg2oVWnJgt2I4+er2stgFTT+vW/XQRWu1zIJYOnefGVAYNWr8lSDJhK3a12zAyxcRg0p/NbD6UGSPuqrBDUZzyUGydUrWaD9D07W7SYP1C21TY8Ay+ZHb60XtQSA0+cuprjQU2+ThrlYUEf41HsyV9kgi0T9RRpnhZedvEJrQ6LhiOg7bMljLcw+38T9adZkaGz0x5pQD1O3wZrBpcNq4Hd+Q7O5Z5PBXwusx7dOJYOtEcO2kXMzi+/zCvTsSU38+AQDz+EgqB858aa+IT0oyXu89Yshtat1oHb8yjzc2kc7koQtVKFDIXNo/HnlA5Ik3GYt9JcwpavT7nrVGC6QltOESRS6OvTeU+pKBIkA7nrymB2mvl0dMscKGxkTYaqUy7vowcvGVKCQPdZ+kWZcj2Kck2CwqIiPEIPb1+/Pf5+7kiGI63SA7Xc/T5vF6MNrz4Vwh6d2e6i1Fb1NYQSBbCXmepWgH3xALGhqcI1Bqh07KvqBXlrPv7t6kuZeai1+J/vCMfjuToiRQXr5XUubf8OSZYx6lw0tc2dHWkBjvXUx7J0jqjBvL39xwkmdRZtJKMz04DKeZlKFGQWXYzrlNaE="
    # GPG_PASSPHRASE
    - secure: "qO+6mxECq2e0al1g/fetNH0mkcHgn60xZfdy2Bj/MdJM1PBm6fVHqA6/fDsy4ADjJnV6QuBbPQ5jnffDpEd90ut1y53pMZ45bV4D6OrNeyfU5a6jQcnL+4rGtbqYZXpgbxWtFyFU50Uz6FOyINhFZWqpBJkQt+CnwwegULjSFzWQQuT9u4o9zsT7aysOsq+FPIEIozKVA09s4UIkwylkihaiVhUXVK70K4F/1xHB5CaUeFDtiA25jVlHs3JnAnSf1Um55g53z7qbe1KqVYgCXY35TANW/ASURF71Tk2qEf31EoIRX2J/ypsVjENrpkQrYdne9cPXpSXwsQf0bNVSaKxn6W/ihCUTXusHnGEfhUFow9xpzwnSuTqhcxF8gKhcZYSws8Fw5nKzTrf4i+CbLcKc/2h4kliO6RmzD9IaaLfFroOYUSzvBXfeXzicyDwpnVMBmJOkRCEBdt+dJzy94+NLksdY09oKVAKPxgNgqwpe7MTVLbANByvrNaXQC1vC6Hfrr2KdGolrySRj3KTaYVv9VSPwHPvLZ6ujpnJPGLayXmqLL5we89+mAew9ZLwcrd2baEc6Ic+xpfbKNa/ehQN7tiBWX9Ks7tvEPUqHtNIFPS6RGv2rtMJcpwL4SFKFqvIsDhEX/lmruePmL6k/G3C+XYXZu622Zy20/M5KETM="
    # CODECOV_TOKEN
    - secure: "Umm0tKXosZmdhLJm4HHTbl/WkmyuS6oFIi0CvopXrL9iQw+zNCgD2P7X6woCmsTMFXEEQKClPqK++JqCQ8hAmXVQZb6K3k41qDeDNWhYIecE/o0conLBQ4v+1vJehPJquzHkZ/EFXs7YJVTGX9MAm3irGcDswRGHHPtxFlf1uVP+DfrYN0t/t0absiX259Z6aM2OkGl8oldaIK5VKyxln6k/dGui++HHyZyLY6B2qeoD8w3PCIMJ6MtBSNAt2NrzhVsj9o4iPWw6Xqvg2O4GLB9UBTBmGzFZBZKfNireqsF5wBjvOXmuiRtFNlRVboULXDkqhogJHamNpXjXv6AHO9vdtsvwDr9GRxUGfeti863gRjQ0RNhp5Y9QQ8okRO/HN84scOMMZF0x45yhiIxmJGbGLWUwuGR6zAmZWftGG6hoIcwVjVHPiV4eUYPgFJJeFRhRE/rPvC+S/vG2qwtjHjO4Rbt6larT/sH1hF8LbrxGhR7J1mIipPAyQaiclpScVpfl3Jx2Di7j5i9dnVsts0bz7fTrofqk/x/iC6RZkRSdkNNbrdmS9CSrNMwSLveK83HPFvS3wtvoULrPJLDq+LPlZj+di8TyXQwj1nrwMSEUExWA5ckSANzJSjefxeKXgocpQ4coi81Icujl/t1pVDLQR5GmlZEgWyHifl7xhS0="
    # TRAVIS_DICEOSS_GITHUB_TOKEN
    - secure: "FT3soD2MLIwrdfmOkJ6HjSKqVs8vp2a6DmEOEsLOYS4yFLibQ9pCMl4BXOUR0lIr1WXQ8v95jmP2dOWhSepOWvZjwPRUtfL5LqSK7AxTgtfQPQrzfDUeBTGY8gWmxqc7RXIPQQghVficP/3iDRxEeqgEQv76XDI9MWcmvVAxH7bDfaD9QfvWbuZGucutZgSfpWDA9KqBOBzqr4ZIkmtRfWFZf1aKnds4wnSe/9XyimSCYdS/m3Ewvprk7utVfkKopRNI9/hScZi7qbp9ZTjKPk1hgGWhd2j4fXPUu5H/LtLSipLALeo1N+UFGfXLxM220KlaL3U4DLD98s5fYocLm9/Y/poCrA6L2lE1jHaK1YVFxqbF558SJx9jCJjhoXkerZwxQMCPIKvRwH/8cW4pq2h69de7c7yxsw0k5B/l+4/vWz8RBlFXbGf0eHjWx7Jynp5Yd2i4MEsg4M+ku09Rznus9q63RGBX2/bW10jHAipdCZZ+wIByJTiWzBTRTEyRn0Q91nt1ZR01wFk2piTQ+csqoc+0CB5yOWvdxKAA2KPzGPQtnt9RqtKGfm1He3hze2eqWr51Zya71gJHHrSAONluPPLbOe6Gl1bFor1pAMSlP5u6VOvp6uEeBJDxoNlCxs+VWgmzqJP0AvGPY/zXd8xu8KGaZDDk8vRgobyYMt8="

cache:
  directories:
    - "~/.m2/repository"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

deploy:
  - provider: script
    script: "./bin/version.sh"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./bin/tag.sh"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./cd/deploy.sh"
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      - dicetechnology: "$encrypted_SLACK_ROOM_API_KEY"
