language: java
jdk:
  - openjdk8

sudo: false

services:
  - docker

branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^issue.*$/"
    - "/^hotfix.*$/"

before_script:
  - "./bin/version.sh"

script:
  - mvn clean install -q || travis_terminate 1

before_install:
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv
    -in gpg.asc.enc -out gpg.asc -d
  - openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv
    -in github.pem.enc -out ~/github.pem -d
  - chmod 600 ~/github.pem
  - eval "$(ssh-agent)"
  - ssh-add ~/github.pem
  - git config core.sshCommand "ssh -i ~/github.pem -F /dev/null"

env:
  global:
    - secure: ZrZhMttwOwJppPBLqT4iev4H+EhGhod3G61niFADurOZJU9jquR6cLu7YQxi+wEnQtfaiPCRRZIO9yopzYQxMvxEX7xDYNKZV9hv1R0B4F1iUJht2BUPzBnpnYBXJRdkQVLDjQLXBrDzW0Em9w075bKC5pcpRccMWclIymJIsty09cwjBxe+r2JG5zAcMCEVH9OISguDwNeE2VB4JAF9cDSEaoeL5zunCeRP7ufbuJhJCczT5/a9yxiDKoSWnWWBbj0FxsSQkj4q461wd1f4tdXFbpYcgTkMZ2d8RiEaM6h05UJ+lxNuMHIWozhwoQv3E9I6qIeX+qMykfHS99f8w/DdLo8HpQgtWRNaTM2qpb5oMwIJAD70YIiBfT7zcppt3Jc8XqJFBMInVrCUsxedRxeBF2CpFJyFeOWKVvvDwiOQiX5W7oLLjlrIIk5c9WYq2FK+arW1ydSU+5LrbrNl/S2PqQRujl0rRI0IkDkj8bVwEQJcef0vm8DQOFsgrAs0ZvpoPI9QtEjCAYW33LwR9RwFwDE+mHTwjoJ27umZ7LTMXDV9upKk8hzF5utDv3wXCiWRsX31a/E1cgRUWlbrNl+z1nFr115WJsJTBh7O+H9HN2VNTVzXEgIh5JQ6g/A+AgEkh+qDBpilyHc7uxbrF4ThrbE5AzGYtE3IzdTI7F8=
    - secure: Ka118fVy58dr5Yh/vF2smKTRBHTC50f4U3p8SYp0DPmeOloL0JjFIcI55TlyM1Mfwk7BcUiKDSo6JCGKfKJ+ZTc2RpCicVYWJuqD/ynsGSV1yL/TaDz5tuXQe25Q8T3B4FhXx5iJd5x5tI2m59bzX+Zm6tuFmrwMrvOlxp7qJ5huKzIRjTwY++vWHG+nrBisHIjAc9PI8J6et4uL+u0Q16eZsWmmpkvP9xd42ZrgFh/a10g3MKwMqakKp9Miy4nv3rF39ww7KCTSszLo/Ash8U1nHawD9qwHvJ+S82T/hLYhUErIP1ONbrZ/KMkpAE7nuXwKtkOsjm2j5/19Chym5+IVmGRQlhShykuLqABDGqUYzCXEtx7KppEyZtI2EctWI8DeoqeCWSzee+aUHgNLcj6tylPFgEZuivgoSmJnQE5xZKNxrUHj+4yWnVqDyspcTMAqAdhnVQPzT/ARxxdWQCX7IeiBEKaNPDDM454g97NZRq3Rlu6HI9r3R/CJ2uJWUTKOlc60fLHLpGrl64Q+Jcegjjk4j4nhTyRNpB4uHNtuCEByHBNJFhwPE9RNc63PoxfQSmYLux53YkO9MTFFfBEc7CrtJHEwq+S0mblzIDLF/mV4lUx/NeonHAfYoJ/DXmUVLwcNIyt1708ACMKl4MQ1ykci3BQDr66RtGgyU9w=
    - secure: Ik893zcoxIshD5k3mS1cPfZltbXAyHmhcUkIvra4Xg9nF3LO5heCxs7XJxXDFlMNRL2AXsaOywkNLOtegeEsnc82GQi3qo+JP5Pqj71NuOsUY5Jygb3W7Kg7UPyVCJPDarmGl5vMAiKUR3ASkD7rA4uLiWIAr25PBBHTgTeQ2+DKYXKiS7jEa8qbM+Ac6hKlFDC5jNTU8dwpOsseoXs6Cq3a4+fNHcO8lsBgv/a1l1pOYpQf1+kDk0Evysw4+CnXLj6gmhKtqCSphXonwTuEmqe5Zn+/WCJr794gankQA4vNS/Wqm2IJGqhsbyjm59SGlBQwWhn6WbSM+IlTPeO/ClVc0nmKJLrs3WyP0PZTnylJXpRIQgUIiN3b38ZizyNFLB6ush/EVhGi01mU00qQpMOBHSMCQHSTzME7zfhJ+mIW22cblxO9OizG/O+xsg5MZLq8FD8C2rfgtkJYlWkZ3UFTZromRchNR84Ztgqc7BpSlci0L1lEKj0meYlfnsVRV5WoIoHlySyUoqumGbU3WCHJPibYNlP1FxHvD7FjAiDDnhtXqqLWIxGleqDChP+dsr0PDeBshqkyE0raRAofHnoEa5bfQNyCZDEyIjmRkVct6vta8QOl4TWEINwB6FKL56lMaysXURYPDq8IiticD+es6Cth5uqMBSykrJaudDk=
    # OSSRH_USERNAME
    - secure: k1dRB5QesVeZPszk4/xR3vqxqXDBk7skd9Brt4CQBFeXGVyRhjgsxwE2X33G4xPMRvakIBTrtq/5O/7WVFMmTFb+cgjYUsJssKqKbIHEkCNVI4zXHgiOfaMElO1MdmwwaUfuXNw/ehYXHp6kBWIqrtUXY4LWbatudzXIJAD0TooCLcVZ4JIfgXGQjzzuqjfukoqX60xvemo9t6zobTYa3tiAb9a9L8elOvGFqFLrsXBakmukcwnvhesNgsucZJGUUn9WvNK6DOwufzosz46XeNbUSDeX0h+23B0SQG3t5cjHUZjYJWW6bl9Zj1s8GIkff+MlNVeIdrisI5e3j/fmb0DyjGP9hKeQSsQT7rdKhUGFvLEOIhyyzqAHhXI2ZLt3vEMmNWE5bQCyT++HFTEI8Z5t6dY3YTw12lJQ1/n4TM6NYhH6500CebBVjqbczxKygnqTUCqqx3hj8sbJ0R4HcqfRKoFq++ZNKeNuIHO+E7mXT0n806foLP3xVfPkAbyV2iqmXRj4ZLCNRY0MGtQTPvcRM+Rk65v8/c16S/Sx8T/CzsWKP7FypfvFjbrSo8HB2+d8agBVyTCAlCkaDtOAHpbW4LjccD+W8mAb1rsoqSX56iD6JtR4jxpMknk7twQO1VsyALmCLD6LEuWxRqwx//FR03rXLQ0YUN11fBhFG4Y=
    # OSSRH_PASSWORD
    - secure: tvB4eDjCVLP0LdgyiX5WUTUyuMD6Flsy/8rsz5fSBcsQN43CtlHMzdychL86kdFSyo9XoRNoH4XdgSkYQXM/8L/qGmPTYdBBI1FXWJ69HN+EYzmGvrYTZrlyxrFYcea25z158BEO2+2vao7II6rFc4mi7PlaUSGbS5cbOEr9bYaZlEC4hZQJkLV0NIIPC+hFnyW5LDR+KEV0tc0Aw/u7YlF5KY3WQB7eq5nROq7/WEmuZsuHVIdn6yH58BgGOFc6KTH8POWvYeuLBzPtFr7bkuE96A6vZEJKfI6VL4BvawQ1wyDWt/5lFbd/sMSgQJrV5QT2BsDWgTY9d8DfGsrtCJ29pB5E2nq/qygU21BugBNQzS92Lt2MPfGUSv9DzVzB8bDXlJNAqTcJxiAvsZpkqxDdaMN9lGCmY+vcmiBUIsrzo+1c7DoAPBHOWUOzjvXCOhElU3wBPhVxUQOdJ+QCDaZ+hvwmjXAZF/1fM9nzdOjKRSPhBTt8wsgBeI4Q8unXHqkKdkUsyvSEbNQ9FhakR0lbtyR6o0/wE/RzwaQh8RM+f+g7rcSfbeaRMS8ORJnnioYPqHVLoBk0J6vr4xQjoqDnDMV598KYbawtpdn9rxA5kahbJSgK9/DKimrIV1mmiMxnrkCEqbzK6rmZhbB5Xk+RflA83r1zbCulSH94Na0=
    # GPG_PASSPHRASE
    - secure: L1/wbH0JbhDrxf3/dijAVABwEkfmthmtJEXX2SAaELx6AIaOfr5r3RTVFEryJ8TOFvSA9vwAUHD/XV7LYTKrVyLDwJ0Qso2tLpeNnbFOYIPqbvAQiBUzAxYv9oJ5urpfO79/IJli0ZmN5S12LParWg78BKvh6JUOjL+fXW6UxDEHObAutQJMAozeJkvLZoSg8jQJBJKIOQqbCGsJS+zINaYr6aJ2dx4oqxLYmepi8VFTuNF9y238nx+R0KZMvOalXW6ZmTHb+jVUq05uqmWap8s3jQi+nPhpLmxce8yQyg3i4/eFmjoXUkEYAhyMoJXiZLcqKYpK2EPAbJcFxrf6BCDOjW7ymKiie5qJnr32FPNdQfv4SRczEz2oOxNONsndEly4dNu9+F+VJx9Z/5boemLuQGABtQ7kM/IfV1PoKFQVVtYQdidlpqGjBfWyW70M8xRMgMzDlbM4dIEuE4MdPoUJKMVHQDyjfi1HLAdVpPLo0WP9TemF9+meAMM3HuSI+inKVRLhz8DIqdRvynRYjZFx2FeZss/ZM3ISqHOCrfDTtvTlzAHbLSZfbV4LMmhXqR0YUUqLNsU/pRDlc6bbV0GYFFgjW9urvjdEVy9yPa4eYhH2b/FE9CMvVzqVOtAJAG434/HqVeF6DQ/CKUr+xfMkFKAon+rpyY58+8IW6hs=

cache:
  directories:
    - "~/.m2/repository"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $encrypted_uuid_repo_token

deploy:
  - provider: script
    script: "./bin/version.sh"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./bin/tag.sh"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./cd/deploy.sh"
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      - dicetechnology: "$encrypted_SLACK_ROOM_API_KEY"
