language: java
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^issue.*$/"
  - "/^hotfix.*$/"

before_script:
- "./bin/version.sh"

script:
- ls -al ~/.ssh
- mvn clean install -q || travis_terminate 1

before_install:
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv -in travis.gpg.pem.enc -out travis.gpg.pem -d
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv -in streaming-machine-user.pem.enc -out streaming-machine-user.pem -d
- gpg --import travis.gpg.pem

env:
  global:
    secure: "veBvTUoZn3OEhoPjKmu3UUd1MSbkMnbkzaJb+8uPlwUY+bn+3Apur/5naETZO/bVRX2PqUGfD3TiNZlnXBdbKGTVceuxlVj0fDlIiuXnayTEiT6PArpqRQAKKadfebtunod8nzeR7VKva+K04MwqQDepb1d9ZLt8hBwrVcE1HPPvkNtNF7b2hZ7eHwX4S2WOWR9Jpy6l5wjM9D+QvBtEiah1ApWUIoS8yk1UA6Z5KyBgrOgpQD0gS9rsJxUv0Ka36tT0Da7pSzClhR0yoTc7g9qrM4F/Bw49IzuDiWdmIsmcpnWe92+IoHuqJzENslhNA/1ijcXpbZldeAc5pCEzVrjLzit33IJ14HuYVnxUfPKnSVNi3I+VQK2CgGf7iyDK7ZsOXOLoHBRB9gyrNJDGsu7tZjWE1bCsGdz47103cvKpZLPO5ug1M5zfknh6MIGmPKK+UZYY9YFrNcNjEbOa5zkKJrSAAqeBsgI8sk/m16QaDn+wlwRaSoMXpQ0MuZAKVp1KRdrfBH3L126oNMr//gd6jMw8Y4HJJY/YpUT25STkcAMCmliC3hiXpnwRTleKssE/cGorjD3YFRuQYK3aqLtsxaeiOVao1ZBQ5pv288onEihfOiPEA5xVd6jUx6jPUInqvYmmsaDxXfQstgNbhwaPJXcaVry1S3D8EzqsjZM="
    secure: "JaAn8/eTWA7OEkGaRCs/VQk9soa23q5txsqPeFRQEB3ql89eMM08L+xu9jA+ZkC38fBKrlqcV13tTU+MjU70eDPFH8NU3e37ZCnyLaBV9J5GsvAZpALRa3T/KfXMNBTJq3E5Ap7xW+sRWK9+PvPUJ7ih7MbiA6au092kJ2CWCu2cAqgK5HWB+HdMaE+qTssmJHHFezTgutTbXtkAcMtOJTrSIvalf/Qc+KnJYQVh3eK8i9HOkEg75YbmgQsArHSlG3J2OX0LmS5KObRRbzHM3OGMpsb6Pi7lYpCE5CByhgSchnKtfRY5gHfXfGu0gdfEWX3mIyHeZ48JTAs6A+QGnhkVIh14Q5KhtcFxwX/Y+MbucTJici4sqdnjRrPIlbXIdt0tZQv38vG+tv+fcNB1vN3/07xJ6a+YFVitaA8VxziMjNUv0OPcmcbj1aWcX2L6VTd91Akb81Jo8NAElCt13rH4+GbOGDD3t2rSzQd6+bVYxXpX9+6aOba3459EEJ0WgsGfkE4w/qZpGye8v/g1Igyn75y/0jdKWBDbR5BYbbUrGLvhXkVITKV6GzdXrqqGu2hRUmxKNTFogZYPI0D8r4Rc+Lzfw9na2FT85AuxQwbmWv4mZv+XjIriQvCnC6BGm7rERSZRFVHVHeIGKwlZKcwyXlx2JNveH5ukCZWX/a4="

cache:
  directories:
  - "~/.m2/repository"

after_success:
- "./bin/version.sh"
- "./bin/tag.sh"

deploy:
- provider: script
  script: "./cd/deploy.sh"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - dicetechnology:zuzWI2typitSKGvP74e6hdCH
