language: java
jdk:
 - openjdk8
sudo: false
branches:
  only:
   - master
   - "/^feature.*$/"
   - "/^issue.*$/"
   - "/^hotfix.*$/"

before_script:
 - ./bin/version.sh

script:
 - ls -al ~/.ssh
 - mvn clean install -q || travis_terminate 1

before_install:
 - openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv -in travis.gpg.pem.enc -out travis.gpg.pem -d
 - gpg --import travis.gpg.pem

env:
  global:
   - secure: F5Ott3nQcYT1arpLOlVI2gZIDFz/v8QUMWZ+MMpYkRiEj0UV7pCTILR94xt03XDkppEvExRoDZIYIa0nsg+EZrz0Lgewy64W4+aG6nmyS+5lTDJMtrTwKCUFAP7e1+0ks+ceVl/KYcUyuwxOXvPtYn+nt0/Ufz68MrJxn7G0Q2z+sB3OlgHr7WwWqM9UuS540APXEMEbxs8kDcABQ40lZ9S7o/nGdEeF2JDKKny5xidyoLCsTgLoFX+tOk8ZDkNnI3goEkSshG4aZIsODpf73b5W/D1XxKaKdn/NWEJP3IIOuPS4Xi+GA8HtIpe+Rw3Qf+SMwuYFu5Xk+R9uu+tSLQihw/UMB4wXXW67ao8EBYretWH8qGegXVvpdEFVWjtS7HVzvrT69TMHc+cW8WCibh29fL1lLo3Ospvd4S8T3iXrG+mHUAEd6niZn1iLhxmw3mHM6iwb3fygVi+wBdWRBGgm5QBASxvUldvIdyI29hNtPQfch77C0Eu3hgeamMbP30WV8+InItUKA302bc9cZKC5KXnTgCcNrVVu8S5Z81+Yqj6OJFZVViYSME/+kEtK9cIQihhw98qk8cjjAVH4juoWUI41f0xccMylRCpNjTpKfAgr4CKJmxKEq0oR+lFPZ/HcrW8JFTYHbRkGldNzgpFPnQdfxw7RWqyyijd/1Z0=
   - secure: R2eMnCDBU/JSNxvXt3Q9SROBc1ovJctZXRcQFmVu9RCHBL6O8SdPeuZp5blwA/4Sy+n6s5iAjT2l5GiX4f7vJDRicih6dEoDQVPVRlOzxcdsMNy+GnkVuwdo2qaA3G3FGHLwwV69pFilomQDZ1oL7COxpno8dILuMfpjLTOXJlL/9IK0PicMCe34IXpzVAGIat3CXpn6YI6CBQ5nJ8sMKoCpOpvhMP0p9iH/h/xMNY37drfY+jwuiJYPfeHDBGaM4JvPtm9JfcHUTxOasQsReLVdI/OcAEqjOrHSH9s8Hjk2eUGfERdhfhPZVPGef21fC4z2ZIBQsmmE849Jf2VJkz0pjJpVDMt/LjQlgOPvBypImWqJayhi+j6hKtddfhsmb5JnOIwFUc91Z6V4jv9Gr6boEDbqQkqrgse+2zSB1eUr1N7z7xpNyNn18ARMJUC8oDaI3FbQqALI82JcKzQmq9la2nctJWcIXrYXtghLe03xsDAQlNVgwl9c0XF2tpbe8OmKAU2CXpOAahlVbVFf8+dG0u1MYI4rXbp4V/UkHShNjbpIV1u8oU47agb53KNa+8rLZ9elO5jCP0Gq0Cpzax2MtFu3jQoqRDOCxYmHB9yeYUllIOTnUkT9KrjGAxP3X4oki6KgAMD1i4YJhn/fnHk1DlcdXMS50iv5zfWSL8g=

cache:
 directories:
  - "~/.m2/repository"

after_success:
 - "./bin/version.sh"
 - "./bin/tag.sh"

deploy:
 - provider: script
   script: ./cd/deploy.sh
   skip_cleanup: true
   on:
    branch: master

notifications:
 slack:
  on_success: never
  on_failure: always
  rooms:
   - dicetechnology:zuzWI2typitSKGvP74e6hdCH
