language: java
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^issue.*$/"
  - "/^hotfix.*$/"
before_script:
- "./bin/version.sh"
script:
- ls -al ~/.ssh
- mvn clean install -q || travis_terminate 1
before_install:
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv
  -in travis.gpg.pem.enc -out travis.gpg.pem -d
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv
  -in github.pem.enc -out github.pem -d
- gpg --import travis.gpg.pem
env:
  global:
    secure: dfmy9nfem2S2JUDycGtdhaMxODo1HydKXlWTJ9QuimlP17ZT4FwcHrtcfjQSt5JhQN9KGZL5M352LrHWrIY4dAPwCwuCh/NjyFawZRBP1Qj/sg2ufZyNnbnZFFocbCAe430AiHqUfthrdmsRwWptV6dLnKNjzSgG0a2AOEjDnUtgIx3XFFjNCAGe9madtgKzz+DfKDbG7cFvQDsdLoKx+/l6dVe4A1yf8KP66TDZbx3B58iGRjbIQL3cgwSRTPSitkinZmD1HorIgGRMbYOr+HNB6G3jUuovDph6wr6gYINVcRdrJfgZkU7V0oSKoDM2yrYjS6P715+Qa7Y3+BGV9D2BI17npVRHKjXCPZkIBKuDOI4ylyDU1Nx4NYvsNj/wVdhUeLUVcU5VJrewQHYimVkWumSLUswKvhXFPQCp5aByTP96zoKFWkbb9hioX4PxHGopsPolkih4OyMILpnTJMONbLbr15xHb0XKvKDSxc+6SeauK3IODBYOl1f/VvCqoRUW1bkwa56V8WE1YGHJBzCsUcntadOvzwFjLvFoobjsYQcAM01isTXjpZEITIio5FgM7xlYouESUBJSY1neLPKVsyWZY3GzN9inmy+4m0HFlb1kB1AUGkltHKVr4GbjKtlhQ5g5suDp3x44008I7sXqCn4uTVp8hFCORCYGfx4=
    secure: AMJw8Mz+Elf+6Bj2S4O6CnnkVnzsjBhgxt/gIUMTTLSryPckZ2iaEoGu4LEYQW/R/exNVirrvWvrFxcFo6eMhCGLyQ73sjCe1GpRGI2A5AVj5C0XCukq9JQ2ugQ+blM8aQBl9r1qKn9oEnL5AlORSQMXcJ4asCKyL5xL3BBzdyYnjwCdKR99KSRpSuGjev7yIpWJQO38oZaq2VW1RohsQ1haT5nzyz52fBO4nsw6C+M9feFq7uEXMKLgT6NbH/N1nfcg0Q/zcCuJyuD5ESlKd1kTWn3TIIC02MKpjI+rT8/mrEshO0pi7WTcJWIYyDz1Tpg8wwR+P8dkbeD6gYPWQcmxpeEelsv8xHFix/3+ZVC3FBrl0HxbCp0qAhKO+u9tA5KrQ9l2HlNNwQ1kkPSrDZMvbdnnTshq15LrFfONJtodnGfFITuSNH0kSEMfvw3brjSNprdUQDD4LACdUnymNL0diRU5AOMcDhn4tluMTYLz3H8W49pmMG64bdlmkdVGAKxCmn4JWnGT67H6H+tA6qcLlOmVHvbGMaGLLmSJZsrcR2bDNNtfS68LbJIuUk7fwZXrqrxHOlmAFYuxy8K4jg0X/CF8i2VwPu0NyU44BJVX1WtqwKIONGsAvTWxRlo4MpfuAMol7ijmKDHSH6BHPmcH1kMwsrAx1B9ERH3y/PY=
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./bin/version.sh"
- "./bin/tag.sh"
deploy:
- provider: script
  script: "./cd/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - dicetechnology:zuzWI2typitSKGvP74e6hdCH
