language: java
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^issue.*$/"
  - "/^hotfix.*$/"

before_script:
 - "./bin/version.sh"

script:
- ls -al ~/.ssh
- mvn clean install -q || travis_terminate 1

before_install:
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv -in travis.gpg.pem.enc -out travis.gpg.pem -d
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv -in streaming-machine-user.pem.enc -out streaming-machine-user.pem -d
- gpg --import travis.gpg.pem

env:
  global:
  - secure: PO1FC6X7oecDF+8Fg7Go7j8QS3Q+lSB0cFiimujACcFsaklhjx3ETn6vxxNZSZzM0NFRTCL4iNuKI51DRCNRBegj7ybMcXJDogFH4XxXjpfifCg8kl2NANCSeJ7K0MygVtWM0Oo5YubyaH8AGDGW351eAswTv9+OnBbia+BiNCOTNdK+DIPW+6R+aD/o+V9YpfmyZl2Wd/w5FWPhJnKfBBNhuKS3r06TJhqJEjhnmBJBEt478xEFoqxKKHviJqxkFZ1UVR/r5U3IGI3tDphZCbwlwjN6ThJXU2UrWUOf1e9Z/uRlT+v779nVFXpA5XBNg6jFnjs8b1cHEM8gDLUBf3Aj3AqoijF+h9X3SjXNVbYsImv9qbjA7n5S7TOAd9vCb9nXc+BDIhDm0jkFknRpvQc3WHEvRWdvvS3SYJNjPJS9WrzTLzPnmCT2Xze1IyfUPOLvW6IO4JYEk3BYL3kqVkNF4O4Xv2mAILniwiWvGrLWKM9wKdqiXcBMLpBudVCwTcJv1lBIJOw7+763+2TZ7vzxUjHFCx58s2oe9iPufjTYAFb6CqXssRzCAqK8iZ2J0qtB19a7dsAXTB/AR3NpM3KhvgLqIVu3byYvQYeibXsud4CQn8SVQvX/B4InzX0dphxZ3evuRomsPLNQ33+NeX8HrFH9LiXcudq6vd7yWKs=
  - secure: r6XS86jCIXf7LLZikV7f+6V0Cy+HtuYTpxoEabMxjs75MaaPopsJytRywi9omro2+cv1Fg0ix9zkKU1L0WWilakvSHKT/bMGV2qeqbA9rUNIaBiaXwL0Uw8ovVemIkBXyAcC9oBp76CVh8xihZwXBvGtdvcZNEMegjmsjmTvvkFmBoZgkQK94e84+50XyvcnOkf4rKWFvAdV6pIYhQnkDUWhihO5C9RfrWjKj69Rzv/TSmFC4rebcWZYUEme5+fPoAEdnOmGgHyWO5gcAOub9ZPhM/JldBnJWa8BBxqSk3Rm5qxMB0K3YFJR1k9P6DS5AsXgqoR3qlcUMefcFpd7fpF/6gvYQU9tvrsUnlRtQmqWf+DPcwCXo5d0vhkkqSOGJ26+YrAZfNL74xbvFDF9ApCzM6A/HPtyy8CDzzUoRe94kHMigH/aaAyHWJ75wcZKP0gDRatlat8ULx3vNW1x2qDRceMyaNri0R1aB7LMu/1AzJNMDhYK1J7PnZji8wBeSYmYV/Z11iywMtvfxjeNhzY512QAKv+dvzL+4L/sgJ3VWnHKWOI0VO4YUKiodwLtYOjMJEcLCjZ1lvZ3AcdAiHOA3ZLWO9wCTu5L2+3tWqCdb+vRKZTJ72jJ61ggFhyzhZdOupWr47KHELsG9/X3htWSLCg+MjPx3MC7gx8ekrU=

cache:
  directories:
  - "~/.m2/repository"

after_success:
- "./bin/version.sh"
- "./bin/tag.sh"

deploy:
- provider: script
  script: "./cd/deploy.sh"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - dicetechnology:zuzWI2typitSKGvP74e6hdCH
