language: java
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^issue.*$/"
  - "/^hotfix.*$/"
before_script:
- "./bin/version.sh"
script:
- ls -al ~/.ssh
- mvn clean install -q || travis_terminate 1
before_install:
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv
  -in github.pem.enc -out ~/github.pem -d
- git config core.sshCommand "ssh -i ~/guthub.pem -F /dev/null"
#- gpg --import travis.gpg.pem

env:
  global:
    secure: ZrZhMttwOwJppPBLqT4iev4H+EhGhod3G61niFADurOZJU9jquR6cLu7YQxi+wEnQtfaiPCRRZIO9yopzYQxMvxEX7xDYNKZV9hv1R0B4F1iUJht2BUPzBnpnYBXJRdkQVLDjQLXBrDzW0Em9w075bKC5pcpRccMWclIymJIsty09cwjBxe+r2JG5zAcMCEVH9OISguDwNeE2VB4JAF9cDSEaoeL5zunCeRP7ufbuJhJCczT5/a9yxiDKoSWnWWBbj0FxsSQkj4q461wd1f4tdXFbpYcgTkMZ2d8RiEaM6h05UJ+lxNuMHIWozhwoQv3E9I6qIeX+qMykfHS99f8w/DdLo8HpQgtWRNaTM2qpb5oMwIJAD70YIiBfT7zcppt3Jc8XqJFBMInVrCUsxedRxeBF2CpFJyFeOWKVvvDwiOQiX5W7oLLjlrIIk5c9WYq2FK+arW1ydSU+5LrbrNl/S2PqQRujl0rRI0IkDkj8bVwEQJcef0vm8DQOFsgrAs0ZvpoPI9QtEjCAYW33LwR9RwFwDE+mHTwjoJ27umZ7LTMXDV9upKk8hzF5utDv3wXCiWRsX31a/E1cgRUWlbrNl+z1nFr115WJsJTBh7O+H9HN2VNTVzXEgIh5JQ6g/A+AgEkh+qDBpilyHc7uxbrF4ThrbE5AzGYtE3IzdTI7F8=
cache:
  directories:
  - "~/.m2/repository"
after_success:
- "./bin/version.sh"
- "./bin/tag.sh"
deploy:
- provider: script
  script: "./cd/deploy.sh"
  skip_cleanup: true
  on:
    branch: master
notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - dicetechnology:zuzWI2typitSKGvP74e6hdCH
dd:
  secure: Ka118fVy58dr5Yh/vF2smKTRBHTC50f4U3p8SYp0DPmeOloL0JjFIcI55TlyM1Mfwk7BcUiKDSo6JCGKfKJ+ZTc2RpCicVYWJuqD/ynsGSV1yL/TaDz5tuXQe25Q8T3B4FhXx5iJd5x5tI2m59bzX+Zm6tuFmrwMrvOlxp7qJ5huKzIRjTwY++vWHG+nrBisHIjAc9PI8J6et4uL+u0Q16eZsWmmpkvP9xd42ZrgFh/a10g3MKwMqakKp9Miy4nv3rF39ww7KCTSszLo/Ash8U1nHawD9qwHvJ+S82T/hLYhUErIP1ONbrZ/KMkpAE7nuXwKtkOsjm2j5/19Chym5+IVmGRQlhShykuLqABDGqUYzCXEtx7KppEyZtI2EctWI8DeoqeCWSzee+aUHgNLcj6tylPFgEZuivgoSmJnQE5xZKNxrUHj+4yWnVqDyspcTMAqAdhnVQPzT/ARxxdWQCX7IeiBEKaNPDDM454g97NZRq3Rlu6HI9r3R/CJ2uJWUTKOlc60fLHLpGrl64Q+Jcegjjk4j4nhTyRNpB4uHNtuCEByHBNJFhwPE9RNc63PoxfQSmYLux53YkO9MTFFfBEc7CrtJHEwq+S0mblzIDLF/mV4lUx/NeonHAfYoJ/DXmUVLwcNIyt1708ACMKl4MQ1ykci3BQDr66RtGgyU9w=
