language: java
jdk:
- openjdk8

sudo: false

branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^issue.*$/"
  - "/^hotfix.*$/"

before_script:
- "./bin/version.sh"

script:
- mvn clean install -q || travis_terminate 1

before_install:
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv
  -in github.pem.enc -out ~/github.pem -d
- chmod 600 ~/github.pem
- eval "$(ssh-agent)"
- ssh-add ~/github.pem
- git config core.sshCommand "ssh -i ~/github.pem -F /dev/null"
#- gpg --import travis.gpg.pem

env:
  global:
    secure: ZrZhMttwOwJppPBLqT4iev4H+EhGhod3G61niFADurOZJU9jquR6cLu7YQxi+wEnQtfaiPCRRZIO9yopzYQxMvxEX7xDYNKZV9hv1R0B4F1iUJht2BUPzBnpnYBXJRdkQVLDjQLXBrDzW0Em9w075bKC5pcpRccMWclIymJIsty09cwjBxe+r2JG5zAcMCEVH9OISguDwNeE2VB4JAF9cDSEaoeL5zunCeRP7ufbuJhJCczT5/a9yxiDKoSWnWWBbj0FxsSQkj4q461wd1f4tdXFbpYcgTkMZ2d8RiEaM6h05UJ+lxNuMHIWozhwoQv3E9I6qIeX+qMykfHS99f8w/DdLo8HpQgtWRNaTM2qpb5oMwIJAD70YIiBfT7zcppt3Jc8XqJFBMInVrCUsxedRxeBF2CpFJyFeOWKVvvDwiOQiX5W7oLLjlrIIk5c9WYq2FK+arW1ydSU+5LrbrNl/S2PqQRujl0rRI0IkDkj8bVwEQJcef0vm8DQOFsgrAs0ZvpoPI9QtEjCAYW33LwR9RwFwDE+mHTwjoJ27umZ7LTMXDV9upKk8hzF5utDv3wXCiWRsX31a/E1cgRUWlbrNl+z1nFr115WJsJTBh7O+H9HN2VNTVzXEgIh5JQ6g/A+AgEkh+qDBpilyHc7uxbrF4ThrbE5AzGYtE3IzdTI7F8=
    secure: Ka118fVy58dr5Yh/vF2smKTRBHTC50f4U3p8SYp0DPmeOloL0JjFIcI55TlyM1Mfwk7BcUiKDSo6JCGKfKJ+ZTc2RpCicVYWJuqD/ynsGSV1yL/TaDz5tuXQe25Q8T3B4FhXx5iJd5x5tI2m59bzX+Zm6tuFmrwMrvOlxp7qJ5huKzIRjTwY++vWHG+nrBisHIjAc9PI8J6et4uL+u0Q16eZsWmmpkvP9xd42ZrgFh/a10g3MKwMqakKp9Miy4nv3rF39ww7KCTSszLo/Ash8U1nHawD9qwHvJ+S82T/hLYhUErIP1ONbrZ/KMkpAE7nuXwKtkOsjm2j5/19Chym5+IVmGRQlhShykuLqABDGqUYzCXEtx7KppEyZtI2EctWI8DeoqeCWSzee+aUHgNLcj6tylPFgEZuivgoSmJnQE5xZKNxrUHj+4yWnVqDyspcTMAqAdhnVQPzT/ARxxdWQCX7IeiBEKaNPDDM454g97NZRq3Rlu6HI9r3R/CJ2uJWUTKOlc60fLHLpGrl64Q+Jcegjjk4j4nhTyRNpB4uHNtuCEByHBNJFhwPE9RNc63PoxfQSmYLux53YkO9MTFFfBEc7CrtJHEwq+S0mblzIDLF/mV4lUx/NeonHAfYoJ/DXmUVLwcNIyt1708ACMKl4MQ1ykci3BQDr66RtGgyU9w=
    # for Slack to send notification (used in tag.sh)
    secure: "s77K0L2hcgLxcuXKnR4sc2zOH1fCXUJ7VJpX5rO2KOnqD8X1VpqyDnsgO6WqFfIyFhmG9vTqOuDoCRl1aG1RQvsW4N5BlmEn+pU85SbyMif8IQ1GrbUJWO1a0umgUiKPpXEi1PUR7dCJgMqLFl0z3pTLooB9JwOzCeVofbyea6g7ea8PgSYTg3Qr0Ycd9ep/hW16R0ij2jucbs1mhytE07o4xkCnOlr6nQ5Bphq1ohcMS3lrW/Xh+6a/P2aguAigeiQpAaVAH+DQGrvg58VxiSkUj/Z62crZz//BOYFoUiahrI/xI3i7bVLe3aUk9UpsOSpJXhV5sflhR2LIP2LWoy2BfRMiPlnPoJ9V9MkresC4U/TLfCEiJco3O0LJgsb2XuHYjyB0VCih2Y1DMamY/7Sx8a3MbfJHjNeRdj1V60DlOi27Y2NO5TqrxzA7JXoPUWSlpNNlOzJflVv0H1R/ZVyJy1Ck6287v+ZU8UVM7/co7s6GZQcw+eAXSocGNxDSHiNr3ryIowa+99tmDAs7clR1WKHSy4JnCGOfArDJThy58gq4v1360JeftyNqGdfhgQFNZ+4DyfO/oC5k6ugGhA39Xvs+luDJWdfdw8DGOaD2e8pbkMvSzy8MDyKLILxNS18AXlCBz3BH/YWOjGXotYsp2Y0Vsqfj1lWx+FYzKmM="

cache:
  directories:
  - "~/.m2/repository"

after_success:
 #

deploy:
- provider: script
  script: "./bin/version.sh"
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: "./bin/tag.sh"
  skip_cleanup: true
  on:
    branch: master
- provider: script
  script: "./cd/deploy.sh"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - dicetechnology:zuzWI2typitSKGvP74e6hdCH
