language: java
jdk:
- openjdk8
sudo: false
branches:
  only:
  - master
  - "/^feature.*$/"
  - "/^issue.*$/"
  - "/^hotfix.*$/"

before_script:
- "./bin/version.sh"

script:
- ls -al ~/.ssh
- mvn clean install -q || travis_terminate 1

before_install:
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv -in travis.gpg.pem.enc -out travis.gpg.pem -d
- openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv -in streaming-machine-user.pem.enc -out streaming-machine-user.pem -d
- gpg --import travis.gpg.pem

env:
  global:
    secure: "W6fR+6BuSVknp/QfrcAVYgWK2kfk4P46A5RbxSckvly8iUj7W98jgSnQSpub3aO68Wy6XvHhRi3FXufdpO7kNEWZsYi+4x5oKhZ3e8NDx96T9lS8MAm7Cx/vby7VLOEk9MDIUQ3xYq29AVcy9oeO6hq+VxxWJwY/9E2+QiK6RLwDhADj8ih2HydLZkoA2wiTvuaMwdst2T0NaG9/2430X/4E5BTBp2chUNLelI1kMd5aCFtJRUa+f7QnAd0SWciFs9uh1fWTINT1hQA0DnOLXXo8zV/Hmzq6frjD2wKRP/nnxCym+LY0/a6mmoCVyHtDya+bUKdDvBWQlx/aFBtT5axZ9PVKBkruNTrgM+6awQ3rt1Zkeqm8wGv9G+N7glyN1/WsjOzKQxrNopVCPK05lAoHD//bboeD34HhxWwodTwjEhqS8qN+9PJJ2oFvTjSijk4fTioj+edLNmfXIWWzyGOhwAKnWsAN9No8YdUYQU9XO2xtXfvdjbWSziZ8H/82G0FlpU7G371Vwt1DVe5zwXn/YfpCsyLk4ef87wpwUlbo+abLJ+qOviDlvkkQzVtOFmc55DUWDFu3VValh8E/lka6jxQrIowL0Pu7q8fbqU5Mpb1WNxgDBdKA4AJmrLRRDzcULjpy77zethQ/JRcfaLwnmZucY2NM4ASGocFkjeU="
    secure: "veBvTUoZn3OEhoPjKmu3UUd1MSbkMnbkzaJb+8uPlwUY+bn+3Apur/5naETZO/bVRX2PqUGfD3TiNZlnXBdbKGTVceuxlVj0fDlIiuXnayTEiT6PArpqRQAKKadfebtunod8nzeR7VKva+K04MwqQDepb1d9ZLt8hBwrVcE1HPPvkNtNF7b2hZ7eHwX4S2WOWR9Jpy6l5wjM9D+QvBtEiah1ApWUIoS8yk1UA6Z5KyBgrOgpQD0gS9rsJxUv0Ka36tT0Da7pSzClhR0yoTc7g9qrM4F/Bw49IzuDiWdmIsmcpnWe92+IoHuqJzENslhNA/1ijcXpbZldeAc5pCEzVrjLzit33IJ14HuYVnxUfPKnSVNi3I+VQK2CgGf7iyDK7ZsOXOLoHBRB9gyrNJDGsu7tZjWE1bCsGdz47103cvKpZLPO5ug1M5zfknh6MIGmPKK+UZYY9YFrNcNjEbOa5zkKJrSAAqeBsgI8sk/m16QaDn+wlwRaSoMXpQ0MuZAKVp1KRdrfBH3L126oNMr//gd6jMw8Y4HJJY/YpUT25STkcAMCmliC3hiXpnwRTleKssE/cGorjD3YFRuQYK3aqLtsxaeiOVao1ZBQ5pv288onEihfOiPEA5xVd6jUx6jPUInqvYmmsaDxXfQstgNbhwaPJXcaVry1S3D8EzqsjZM="

cache:
  directories:
  - "~/.m2/repository"

after_success:
- "./bin/version.sh"
- "./bin/tag.sh"

deploy:
- provider: script
  script: "./cd/deploy.sh"
  skip_cleanup: true
  on:
    branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
    - dicetechnology:zuzWI2typitSKGvP74e6hdCH
