language: java
jdk:
  - openjdk8

sudo: false

services:
  - docker

branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^issue.*$/"
    - "/^hotfix.*$/"

before_script:
  - "./bin/version.sh"

script:
  - mvn clean install -q || travis_terminate 1

before_install:
  - openssl aes-256-cbc -K $encrypted_044baa266d1a_key -iv $encrypted_044baa266d1a_iv
    -in gpg.asc.enc -out gpg.asc -d
  - openssl aes-256-cbc -K $encrypted_c423d447bd66_key -iv $encrypted_c423d447bd66_iv
    -in github.pem.enc -out ~/github.pem -d
  - chmod 600 ~/github.pem
  - eval "$(ssh-agent)"
  - ssh-add ~/github.pem
  - git config core.sshCommand "ssh -i ~/github.pem -F /dev/null"

env:
  global:
    # OSSRH_USERNAME
    - secure: k1dRB5QesVeZPszk4/xR3vqxqXDBk7skd9Brt4CQBFeXGVyRhjgsxwE2X33G4xPMRvakIBTrtq/5O/7WVFMmTFb+cgjYUsJssKqKbIHEkCNVI4zXHgiOfaMElO1MdmwwaUfuXNw/ehYXHp6kBWIqrtUXY4LWbatudzXIJAD0TooCLcVZ4JIfgXGQjzzuqjfukoqX60xvemo9t6zobTYa3tiAb9a9L8elOvGFqFLrsXBakmukcwnvhesNgsucZJGUUn9WvNK6DOwufzosz46XeNbUSDeX0h+23B0SQG3t5cjHUZjYJWW6bl9Zj1s8GIkff+MlNVeIdrisI5e3j/fmb0DyjGP9hKeQSsQT7rdKhUGFvLEOIhyyzqAHhXI2ZLt3vEMmNWE5bQCyT++HFTEI8Z5t6dY3YTw12lJQ1/n4TM6NYhH6500CebBVjqbczxKygnqTUCqqx3hj8sbJ0R4HcqfRKoFq++ZNKeNuIHO+E7mXT0n806foLP3xVfPkAbyV2iqmXRj4ZLCNRY0MGtQTPvcRM+Rk65v8/c16S/Sx8T/CzsWKP7FypfvFjbrSo8HB2+d8agBVyTCAlCkaDtOAHpbW4LjccD+W8mAb1rsoqSX56iD6JtR4jxpMknk7twQO1VsyALmCLD6LEuWxRqwx//FR03rXLQ0YUN11fBhFG4Y=
    # OSSRH_PASSWORD
    - secure: tvB4eDjCVLP0LdgyiX5WUTUyuMD6Flsy/8rsz5fSBcsQN43CtlHMzdychL86kdFSyo9XoRNoH4XdgSkYQXM/8L/qGmPTYdBBI1FXWJ69HN+EYzmGvrYTZrlyxrFYcea25z158BEO2+2vao7II6rFc4mi7PlaUSGbS5cbOEr9bYaZlEC4hZQJkLV0NIIPC+hFnyW5LDR+KEV0tc0Aw/u7YlF5KY3WQB7eq5nROq7/WEmuZsuHVIdn6yH58BgGOFc6KTH8POWvYeuLBzPtFr7bkuE96A6vZEJKfI6VL4BvawQ1wyDWt/5lFbd/sMSgQJrV5QT2BsDWgTY9d8DfGsrtCJ29pB5E2nq/qygU21BugBNQzS92Lt2MPfGUSv9DzVzB8bDXlJNAqTcJxiAvsZpkqxDdaMN9lGCmY+vcmiBUIsrzo+1c7DoAPBHOWUOzjvXCOhElU3wBPhVxUQOdJ+QCDaZ+hvwmjXAZF/1fM9nzdOjKRSPhBTt8wsgBeI4Q8unXHqkKdkUsyvSEbNQ9FhakR0lbtyR6o0/wE/RzwaQh8RM+f+g7rcSfbeaRMS8ORJnnioYPqHVLoBk0J6vr4xQjoqDnDMV598KYbawtpdn9rxA5kahbJSgK9/DKimrIV1mmiMxnrkCEqbzK6rmZhbB5Xk+RflA83r1zbCulSH94Na0=
    # GPG_PASSPHRASE
    - secure: L1/wbH0JbhDrxf3/dijAVABwEkfmthmtJEXX2SAaELx6AIaOfr5r3RTVFEryJ8TOFvSA9vwAUHD/XV7LYTKrVyLDwJ0Qso2tLpeNnbFOYIPqbvAQiBUzAxYv9oJ5urpfO79/IJli0ZmN5S12LParWg78BKvh6JUOjL+fXW6UxDEHObAutQJMAozeJkvLZoSg8jQJBJKIOQqbCGsJS+zINaYr6aJ2dx4oqxLYmepi8VFTuNF9y238nx+R0KZMvOalXW6ZmTHb+jVUq05uqmWap8s3jQi+nPhpLmxce8yQyg3i4/eFmjoXUkEYAhyMoJXiZLcqKYpK2EPAbJcFxrf6BCDOjW7ymKiie5qJnr32FPNdQfv4SRczEz2oOxNONsndEly4dNu9+F+VJx9Z/5boemLuQGABtQ7kM/IfV1PoKFQVVtYQdidlpqGjBfWyW70M8xRMgMzDlbM4dIEuE4MdPoUJKMVHQDyjfi1HLAdVpPLo0WP9TemF9+meAMM3HuSI+inKVRLhz8DIqdRvynRYjZFx2FeZss/ZM3ISqHOCrfDTtvTlzAHbLSZfbV4LMmhXqR0YUUqLNsU/pRDlc6bbV0GYFFgjW9urvjdEVy9yPa4eYhH2b/FE9CMvVzqVOtAJAG434/HqVeF6DQ/CKUr+xfMkFKAon+rpyY58+8IW6hs=
    # CODECOV_TOKEN
    - secure: Umm0tKXosZmdhLJm4HHTbl/WkmyuS6oFIi0CvopXrL9iQw+zNCgD2P7X6woCmsTMFXEEQKClPqK++JqCQ8hAmXVQZb6K3k41qDeDNWhYIecE/o0conLBQ4v+1vJehPJquzHkZ/EFXs7YJVTGX9MAm3irGcDswRGHHPtxFlf1uVP+DfrYN0t/t0absiX259Z6aM2OkGl8oldaIK5VKyxln6k/dGui++HHyZyLY6B2qeoD8w3PCIMJ6MtBSNAt2NrzhVsj9o4iPWw6Xqvg2O4GLB9UBTBmGzFZBZKfNireqsF5wBjvOXmuiRtFNlRVboULXDkqhogJHamNpXjXv6AHO9vdtsvwDr9GRxUGfeti863gRjQ0RNhp5Y9QQ8okRO/HN84scOMMZF0x45yhiIxmJGbGLWUwuGR6zAmZWftGG6hoIcwVjVHPiV4eUYPgFJJeFRhRE/rPvC+S/vG2qwtjHjO4Rbt6larT/sH1hF8LbrxGhR7J1mIipPAyQaiclpScVpfl3Jx2Di7j5i9dnVsts0bz7fTrofqk/x/iC6RZkRSdkNNbrdmS9CSrNMwSLveK83HPFvS3wtvoULrPJLDq+LPlZj+di8TyXQwj1nrwMSEUExWA5ckSANzJSjefxeKXgocpQ4coi81Icujl/t1pVDLQR5GmlZEgWyHifl7xhS0=

cache:
  directories:
    - "~/.m2/repository"

after_success:
  - bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

deploy:
  - provider: script
    script: "./bin/version.sh"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./bin/tag.sh"
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: "./cd/deploy.sh"
    skip_cleanup: true
    on:
      branch: master

notifications:
  slack:
    on_success: never
    on_failure: always
    rooms:
      - dicetechnology: "$encrypted_SLACK_ROOM_API_KEY"
